class Activity {
  final int customerId;
  final int supplierId;
  final String activityNumber;
  final String subject;
  final int userId;
  final int categoryId;
  final int priorityId;
  final int statusId;
  final int roleId;
  final String startedOn;
  final String completedOn;
  final String dueOn;
  final String description;
  final int activityType;
  final bool autoGenerated;
  final bool useAutomaticNumbering;
  final bool isAutomatic;
  final List<dynamic> contacts;
  final List<dynamic> caseFiles;
  final List<dynamic> documents;
  final List<dynamic> activities;
  final List<dynamic> extendedProperties;
  final String createdBy;
  final String creationDateTime;
  final String lastModifiedBy;
  final String lastModifiedDateTime;
  final int id;

  Activity(
      this.customerId,
      this.supplierId,
      this.activityNumber,
      this.subject,
      this.userId,
      this.categoryId,
      this.priorityId,
      this.statusId,
      this.roleId,
      this.startedOn,
      this.completedOn,
      this.dueOn,
      this.description,
      this.activityType,
      this.autoGenerated,
      this.useAutomaticNumbering,
      this.isAutomatic,
      this.contacts,
      this.caseFiles,
      this.documents,
      this.activities,
      this.extendedProperties,
      this.createdBy,
      this.creationDateTime,
      this.lastModifiedBy,
      this.lastModifiedDateTime,
      this.id);

  Activity.fromJson(Map<String, dynamic> json)
      : customerId = json['CustomerId'] as int,
        supplierId = json['SupplierId'] as int,
        activityNumber = json['ActivityNumber'] as String,
        subject = json['Subject'] as String,
        userId = json['UserId'] as int,
        categoryId = json['CategoryId'] as int,
        priorityId = json['PriorityId'] as int,
        statusId = json['StatusId'] as int,
        roleId = json['RoleId'] as int,
        startedOn = json['StartedOn'] as String,
        completedOn = json['CompletedOn'] as String,
        dueOn = json['DueOn'] as String,
        description = json['Description'] as String,
        activityType = json['ActivityType'] as int,
        autoGenerated = json['AutoGenerated'] as bool,
        useAutomaticNumbering = json['UseAutomaticNumbering'] as bool,
        isAutomatic = json['IsAutomatic'] as bool,
        contacts = json['Contacts'] as List<dynamic>,
        caseFiles = json['CaseFiles'] as List<dynamic>,
        documents = json['Documents'] as List<dynamic>,
        activities = json['Activities'] as List<dynamic>,
        extendedProperties = json['ExtendedProperties'] as List<dynamic>,
        createdBy = json['CreatedBy'] as String,
        creationDateTime = json['CreationDateTime'] as String,
        lastModifiedBy = json['LastModifiedBy'] as String,
        lastModifiedDateTime = json['LastModifiedDateTime'] as String,
        id = json['Id'] as int;

  Map<String, dynamic> toJson() => {
        'customerId': customerId,
        'supplierId': supplierId,
        'activityNumber': activityNumber,
        'subject': subject,
        'userId': userId,
        'categoryId': categoryId,
        'priorityId': priorityId,
        'statusId': statusId,
        'roleId': roleId,
        'startedOn': startedOn,
        'completedOn': completedOn,
        'dueOn': dueOn,
        'description': description,
        'activityType': activityType,
        'autoGenerated': autoGenerated,
        'useAutomaticNumbering': useAutomaticNumbering,
        'isAutomatic': isAutomatic,
        'contacts': contacts,
        'caseFiles': caseFiles,
        'documents': documents,
        'activities': activities,
        'extendedProperties': extendedProperties,
        'createdBy': createdBy,
        'creationDateTime': creationDateTime,
        'lastModifiedBy': lastModifiedBy,
        'lastModifiedDateTime': lastModifiedDateTime,
        'id': id
      };
}
